source 'https://rubygems.org'

gem 'rack'
gem 'activerecord', '~> 5.0'
gem 'haml'
gem 'sass'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-attack'

group :development, :test do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
end